gemfile: 'Gemfile'

PostCheckout:
  BundleInstall:
    enabled: true

PreCommit:
  # Checks for vulnerable versions of gems
  BundleAudit:
    enabled: true
    on_warn: fail

  # Dependency Check
  BundleCheck:
    enabled: true
    on_warn: fail

  # Style checker for CoffeeScript
  CoffeeLint:
    enabled: true
    on_warn: fail

  # Style Check in HAML
  HamlLint:
    enabled: true
    on_warn: fail

  # Checks for hard tabs in files
  HardTabs:
    enabled: true
    on_warn: fail

  # Migration Check
  RailsSchemaUpToDate:
    enabled: true
    on_warn: fail

  # Style Check
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop', '-c', './.rubocop.yml']
    on_warn: fail

  # YAML Check
  YamlSyntax:
    enabled: true
    on_warn: fail

PrePush:
  # Security Check
  Brakeman:
    enabled: true
    command: ['bundle', 'exec', 'brakeman']
    on_warn: fail

  BundleInstall:
    enabled: true
    on_warn: fail

  # Unit & Integration TEST
  RSpec:
    enabled: true
    command: ['bundle', 'exec', 'rspec', 'spec']
    on_warn: fail
